C_LİST=[
	"Seçdiyiniz bir sosial media hesabından çox çirkin bir şəkil paylaşın.","Telefonunuzdakı mesaj bölməsini açın, gözlərinizi yumun və təsadüfi bir adama random bir mesaj göndərin.",
	"Növbəti 5 dəqiqə ərzində söylədiyiniz hər şeydən sonra "məə" deyəcəksiniz",
	"Önümüzdəki 5 dəqiqədə kiminsə heyvanı olun.","İnstagramınızı oyunçulardan birinə verin. Hər yerə 5 dəqiqə baxmaq sərbəstdir.",
	"Oyundan bir insana serenad edin (oğlan qız olarsa, qız oğlan olarsa)","Növbəti 3 növbədə ləhcə ilə danışın.",
	"3 dəqiqəlik uşaq olun!","Telefonunuzdaki ən sevmədiyiniz şəkili göndərin","Sevdiyiniz şəkli göndərin",
	"Whatsapp da 2 söhbətinizi göstərin","Şəxsi mesajlarınızı əldə edin və qrupa göndərin","Whatsapp -da son söhbətinizi bura atın",
	"Bir dəftərə 20 dəfə "mən malam" yaz və şəklini at","Telegramda son söhbətinizi bura atın","Biona +18 bir cümlə yaz; 31 dəqiqə qalmalıdı.!",
	"Galerinin bir hissəsini ss alıb bura at","Galerindəki 16-cı şəkili at.","Instagram ya da telegramdan tanımadığın birinə gülməli olmuyan bir lətifə danış.",
	"Layla oxuyaraq səs at","Bugünüvə aid qısa bir hekayə qur.","Whatsapp’da danışdığın adamların ssini at",
	"Qrupun istifadəçilər siyahısına gir ve 7-ci adama anlıq at.","Ən son danışdığın adama \"Dayıgil necədi?\" deyə mesaj at.",
	"İndiki halının şəkilini çəkib at","Qrupda istifadəçilər yerinə gir 11-ci adama \"Akulalar oyaqdılar, yatmayıblar\" deyə səs at və cavabını qrupla paylaş.",
	"Profil şəkilinə nifrət elədiyin bir məşhurun şəkilini qoy.","Başında yumurta qır və fotosunu at",
	"Qrupdan sevdiyin bir adamın şəkilini profil şəkilivə qoy","Balkona vəya pəncərəyə çıx çöldəkilərin eşidəcəyi şəkilde mahnı oxu videoya çək qrupa at.",
	"Etiraf elə: adam daşımaq üçün neçə hesabın var?","Qrupdaki 5 oğlana/qıza səni sevirəm de","İki dəqiqəlik toyuq ol.","Seçdiyiniz bir heyvanı təqlid edin.",
	"Seçtiyin bir əşyanı yalayın və qrupa fotosunu atın.","Qrupa utanc verən bir şəkilini göstər.",
	"Çirkin bir selfie çək və sosial medya proqramlarından birində paylaş 1 saat qalacaq.","Bir qaşıq un ye və video ya çək qrupa at",
	"Heç tanımadığın birinə Səni sevirəm deyin","Sevdiyin bir adama \"`Mən səni necə sevdim necə bağlandım bilmirəm ama yene də sevirəm səni <3`\" de. Cavab gələndə qrupta paylaş biz də görək",
	"Telegram'daki ən çox adam olan qrupu aç və \"`Mənim adım yas samovarıdı!`\" deyərək səs göndər.","Həmcinsin olan yaxın bir dostuna onu sevdiyini de.","Qrafinkadan su iç və foto at.",
	"Ən çox danışdığın qız/oğlan dostuna \" `Səni çox sevirəm deyəsən aşiq olmuşam`\" yaz və cavabını bizimlə paylaş",
	"Adıvı 1 saatlıq 31<adın> et. (məsələn adın TheZahid isə 31TheZahid et)","İnstagram'da dm qutusunu (mesajlar hissəsini) ss al qrupa at.",
	"Tanımadığın birinə bu cümləni atıb söhbət başlat: \"`Sevgimizin okeanda boğulacağını bilsəydim Okean olardım`\"",
	"Ən gülməli şəkilini qrupla paylaş.","Qrupta İstifadəçilər siyahısına gir 11-ci adama \"`Səni tutsam çox sevəcəm <3`\" deyə səs at və cavabını qrupla paylaş.",
	"Tanımadığın birinə bu mesajı at sonra cavabını qrupla paylaş ➡️\n  \"`Bu mesaj özəl bir serverlə göndərilmişdir. Ağıllılarda unutqanlıq, Giclərdə korluq, ibnələrdə də bir anlıq gülüş yaradar!`\"",
	"@ yaz çıxan ilk adamı etiketlə və səni sevirəm yaz.","Tanımadığın birinə \" `Deyəsən sənə aşiq olmuşam`\" deyə mesaj at.",
	"Telegramın haqqında bölməsinə \"`SeVgİLiSiNiNiN alPHeN GoLDhU`\" yaz 1 saatlıq qalsın.","Google/Youtube/İnstagram axtarış keçmişini ss et və bura at",
	"Galerinin ən alt hissədən 7-ci Fotonu göndər",
	"Sonraki 3 tur ləhcə ilə danış.",
	"Üç sup qaşığı acı tomat (vəya buna oxşuyan bir şey) ye və video çək qrupa at",
	"5 dəqiqəlik oyundaki bir nəfərin evcil heyvanı olmasını de.","Yeri yala və şəkilini/videosunu qrupa at",
	"3 dəqiqəlik bir məhşuru təqlid et.", "Kimsə təqlid edilən məhşuru təxmin edənə qədər bir məhşuru təqlid et",
	"Qrupun ortaya qoyduğu bir mövzü ətrafında 3 sətır və 1 misralıq bir şeir yaz",
	"Oyundaki adamların ortaq qərarıyla qruptan birini öp səs ataraq.",
	"5 dəqiqəlik oyundaki bir nəfərin qulu ol.", "Bir süpürgə vəya paspas ilə rəqs et və videosunu at",
	"Əsl sevdiyinin kim olduğunu elan et","Ağzını hərəkət ettirmədən başdan sona əlifbanı oxu oxuyarkən video at", "Ağlına gələn ilk sözü de.",
	"Oyundaki oyunçulardan biri haqqında bəhanə uydur", "15 saniye içində sondan başa əlifbanı oxu oxuyarkən səs at", "İt kimi havlayaraq səs at",
	"Bir mahnını başdan sona oxuyarkən səs at","Sevgili olduğun yaxşı və pis birini de.",
	"Bir dəqiqəlik qarşı cinstən biri kimi gəz.","İndi sevdiyin adamın baş hərfini de Özü anlasın","@TheZahid ə onu tanıyıb/tanımadığını de","Sevdiyin adamın adını səs atıb qışqıraraq de",
]

D_LİST = [
	"Telefonunuza son axtardığınız şey nə idi?", "Biri qız yoldaşınızdan/sevgilinizdən ayrılmaq üçün sizə 1 milyon dollar təklif etsə, qəbul edərsinizmi?",
"Bu qrupda ən çox kimdən xoşunuz gəlir və niyə?", "Heç sinifdə yüksək səslə ağlamısınızmı?",
"Dərsdə nə zaman yüksək səslə ağlamısanmı?", "Yerdən bir şey götürüb yedinmi?",
"Bir gün əks cins olaraq oyansan, ilk növbədə nə edərsən?",
"Hovuzda işəmisinizmi?", "Heç liftdə qaz buraxmısınızmı?",
"Tualetdə oturanda ilk ağla gələn şeylər nələrdir?", "Sizlə Böyüyən xəyali bir dostun varmı?",
"Ən pis vərdişiniz nədir?", "Burnunuzu qarışdırırsınızmı?", "Hamamda mahnı oxuyursan?",
"Heç üstüvə işəmisənmi?", "İctimai yerlərdə ən utanc verici anın nə idi?", "Heç güzgüdə özünlə danışmısanmı?",
"Kimsə veb tarixçənizi görsəydi nədən utanardınız?", "Yuxuda danışırsınız?",
"Gizli eşqiniz kimdir?", "Özünüzdə nəyi bəyənmirsiniz?", "Hazırda hansı rəngli alt paltarı geyinirsiniz?",
"Ən son göndərdiyiniz mesaj nə idi?", "İnsanları yanan binadan xilas edirsinizsə və bu qrupdan bir nəfəri geridə qoymalı olsaydınız, kim olardı?",
"Alt paltarınızı nə qədər tez -tez yuyursunuz?", "Qulaqcığın dadını heç hiss etmisinizmi?",
"Nə vaxtsa başqasını qınadın və günahlandırmısan?", "Heç tərini dadmısanmı?",
"Bu otaqda kim ən pis adam olardı? və Niyə?",
"Yenidən doğulsaydınız, hansı əsrdə doğulmaq istərdiniz?", "Əgər dediyiniz və ya etdiyiniz bir şeyi silmək üçün geriyə gedə bilsəydiniz, hansı il olardı?",
"Sevgilin və ya sevgilin səni heç vaxt utandırıbmı?", "Birdən görünməz adam olsan nə edərdin?",
"Hamamda qaldığın ən uzun müddət və niyə bu qədər uzun müddət qaldın?", "İndiyə qədər gördüyüm ən qəribə yuxudan danış.",
"Duşda işəyirsənmi?", "Hələ də etdiyin ən uşaqcasına iş nədir?", "Hansı uşaq filminə dəfələrlə baxmısan?",
"Pis ayaq qoxunuz varmı?", "Mənasız ləqəbləriniz varmı?", "Telefonunuzda ən çox neçə vaxt keçirmisiniz?",
"Bir oturuşda yediyiniz ən çox yemək nədir?", "Tək qalanda rəqs edirsinizmi?", "Qaranlıqdan qorxursunuz?",
"Bütün günü evdə olsaydınız nə edərdiniz?", "Gündə neçə selfi çəkirsiniz?", "Sonuncu dəfə nə vaxt dişlərinizi fırçaladınız?",
"Ən sevdiyiniz pijama nə kimi görünür?",
"Bədəninizin hansı hissəsini sevirsiniz, nədən nifrət edirsiniz?", "Heç bitləriniz olubmu?",
"Heç şalvarını özün kəsmisənmi?", "Tabağını yalayırsan?", "Sənin haqqında heç kimin bilmədiyi bir şey nədir?",
"Heç boşqabınızı yaladınızmı?", "Dirsəyinizi yalaya bilərsinizmi?", "Buradakı hər kəsi yanan bir binadan qurtarmağa çalışsaydınız və kimisə geridə qoymalı olsaydınız, kimləri geridə qoyardınız?",
"Telefonda axtardığınız son şey nə idi?", "Telefonunuzdan bir tətbiq silməli olsaydınız, hansını silərdiniz?", "Bir əlaqədə ən böyük qorxunuz nədir?",
"Otaqdakı hər bir insan haqqında bir müsbət və bir mənfi şey söyləyin.", "Bəyənmədiyiniz pis vərdişiniz varmı?",
"Həyatınızda etdiyiniz ən çılğın şey nədir?", "Üç gün bir adada qalsaydınız, bu qrupdan kimləri seçərdiniz?",
"Bu qrupdaki ən əsəbi adam kimdir?", "Bu qrupdan biriylə evlənmək məcburiyyətindəsinizsə, kim olardı?", "Ən uzun münasibətiniz nə qədərdi?",
"İnstaqramda sizi bir məşhur izləsəydi, bu məşhurun kim olmasını istərdiniz?", "İnstagramda 5 nəfəri silməli olsaydınız, kimləri silərdiniz?",
"Neçə uşaq sahibi olmaq istəyirsən?", "Xəyallarındakı adamı təsvir et.", "Messi yoxsa Ronaldo?", "Pes2013 yoxsa Fifa?",
"İlk işiniz nə idi?", "Kollec haqqında ən böyük qorxunuz nədir?", "Ən yaxın dostunuzun sizinlə eyni universitetə getməsini istərdinizmi?",
"İndiki sevgilinizin və ya qız yoldaşınızın sizinlə eyni universitetə getməsini istərdinizmi?", "Xəyalınızdakı iş nədir?",
"Hələ bir dərsi buraxmısınızmı?", "Heç aldatmısınızmı?", "Heç sinifdə yatmısınızmı?", "Kimin sinifdə yanında oturmaq istəməyəcəyiniz kimdir?",
"Heç dərsə gecikmisinizmi?", "Müəllimin qarşısında etdiyiniz ən utanc verici şey nədir?", "Masanın altına saqqız qoymusunuzmu?",
"Məktəbdə heç dava etdinizmi?", "Testdə ən pis balınız hansı idi?", "Heç sinifdə yuxuya getmisinizmi?", "Heç saxlanılıbmı?",
"Görünməz olsaydınız hansı sinfə girərdiniz?", "Hansı qrup ən pisdir?", "Bu qrupda sirr saxlamaqda ən çox kim çətinlik çəkir?",
"Son dediyin yalan nə idi?", "İdman edirsənmi?", "Ömrünün sonuna qədər yalnız bir paltar geyə bilsəydin, nə rəng olardı?",
"Sizcə, Türkiyənin təhsil sistemində edilməsi lazım olan ən əhəmiyyətli dəyişiklik nədir?", "Qaranlıqdan/yüksəklikdən qorxursunuz?",
"1 -dən 10 -a qədər öz görünüşünüzü qiymətləndirin :)", "Etdiyiniz ən qanunsuz şey nə idi?", "İndi bəyənmədiyiniz biri ilə evlilik təklifiniz varsa və bu son evlilikdirsə sizə təklif, qəbul edərsinizmi? ",
"Mövcud əhvalınıza əsaslanaraq hansı filmə baxırsınız (aksiya/dram/elmi-fantastik/romantik komediya/tərcümeyi-hal/fantaziya)",
"Ən çox əzildiyini hiss etdiyin an hansı idi?", "Gələcəkdə bir uşağın olsaydı nə ad vermək istərdin?",
"Tək boynuzlu və ya əjdaha sahibi olmaq istərdinizmi?", "Neçə sevgilin olub?","Həyatında unutmadığın biri varmı? ",
"sevdiyiniz mahnı?", "Etməməyiniz lazım olan bir şeylə heç yaxalanmısınızmı?", "Ən sevdiyiniz sənətçi kimdir?",
"Qarşı cinsdə ilk olaraq diqqətinizi çəkən nədir?", "Bu il həyatınızda nəyi dəyişməyi uyğun görürsünüz?",
"Birinin telefonunda gördüyün ən qəribə şey nədir?", "Super qəhrəmanlar həqiqətən də olsaydı dünya necə olardı?",
"Həyatın sənə öyrətdiyi ən vacib dərs nədir?", "Mədəniyyətimizin ən çox sevdiyin hissəsi nədir?", "Ailənin ən qəribə ənənəsi nədir?",
"Ailənizdən başqa, həyatınıza ən böyük təsir edən kimdir?", "Qadın/kişi olmağın ən pis və ən yaxşı tərəfi nədir?",
"Beyninizi bir robotun içinə qoyub sonsuza qədər belə yaşaya bilsəydiniz, bunu edərdinizmi?", "Evinizdə yaşadığınız ən pis qonaq kim idi və nə oldu?",
"İnsanlardan sənə nə soruşmaqdan yoruldun?", "Ən qəribə qorxun nədir?", "Ən çox sevdiyin TV şou nədir?", "İndiyə qədər yaşadığın ən axmaq mübahisə nədir?",
"Son dediyin yalan nədir?", "Tanışlıqda etdiyin ən utanc verici şey nə idi?",
"Heç təsadüfən avtomobilinizlə bir şeyə və ya kiməsə vurdunuzmu (əgər varsa)?",
"Bəyəndiyinizi düşündüyünüz, amma davam edə bilməyəcəyiniz biri olubmu?", "Ən qəribə ləqəbiniz nədir?",
"Fiziki olaraq ən ağrılı təcrübəniz nə idi?"
"İctimai nəqliyyatda etdiyiniz ən çılğın şey nədir?", "Şişədən bir cin çıxsaydı üç istəyiniz nə olardı?", "Dünyada kimisə Türkiyə prezidenti edə bilsəydiniz, kim edərdi? olmaq? ",
"Başqasına dediyin ən qəddar söz nədir?", "Birini öpərkən özünü pis hiss etmisənmi?", "Bunun heç bir nəticəsi olmayacağını bilsəydin nə edərdin?",
"Bir güzgü qarşısında etdiyin ən çılğın şey nədir?", "Başqasına dediyin ən mənalı şey nədir?",
"Dostlarınızla nə etməyi sevirsiniz, amma heç vaxt sevgilinizin gözü qarşısında etməzsiniz?", "Bu həyatda ən çox kimə qısqanırsınız?",
"Ən sevdiyiniz pijamalar nəyə bənzəyir?", "Görüşməmək üçün heç vaxt xəstə kimi davranmısınızmı?", "Görüşdüyünüz ən yaşlı insan kimdir?",
"Gündə neçə selfi çəkirsən?", "Gündə neçə selfi çəkirsən?", "Həftədə neçə dəfə eyni şalvar geyinirsən?",
"Bu gün şansınız olsaydı, liseyinizlə tanış olardınızmı?", "Bədəninizin hansı hissəsini qıdıqlayırsınız?",
"Müxtəlif xurafatlarınız varmı? Əgər belədirsə, bunlar nədir?", "Hansı filmi sevdiyinizi etiraf etməkdən utanırsınız?", "Ən utanc verici özünə qulluq vərdişiniz nədir?", "Ən son nə vaxt nəyə görə üzr istədim? "," Şifahi dastanlar haqqında nə düşünürsən? ",
"Ən çox utanc verici qoxular hardan qaynaqlanır?", "Qız yoldaşına danışmaq haqqında heç düşünmüsənmi?", "Qız yoldaşını heç kimlə aldatmısanmı?", "Boksçu və ya külot?", "Heç işəmisənmi? hovuzda və ya dənizdə? "," Saçlarınızı heç uzatmısınızmı? Nə vaxta qədər davam edəcəyini düşünürsünüz? "," Heç kimin bilməyəcəyinə zəmanət verilsəydi kimləri öldürərdin? "," Ən ucuz hədiyyəniz nədir? Heç başqası üçün almısan? "
"Vaxtınızın çoxunu hansı tətbiqə sərf edirsiniz?", "Avtobusda etdiyiniz ən qəribə şey nədir?", "Heç ictimai yerlərdə çılpaq olmusunuzmu?", "Gündə nə qədər dedi -qodu edirsiniz?", " Görüşmək istədiyin ən gənc adam neçə yaşında olardı?",
"Yaşınızla bağlı yalan danışmısınızmı?", "Telefonunuzdan bir tətbiq silməli olsaydınız, nə olardı?",
"Gecə gec etdiyiniz ən utanc verici şey nədir?", "Duş almadan getdiyiniz ən uzun müddət nədir?", "Heç saxta şəxsiyyət vəsiqəsi istifadə etmisinizmi?","İstədiyiniz ünlü kimdir? qırmızı xalça ilə gəzmək? "," Gizli eşqiniz kimdir? "
] 
